"""Add notes column to Contact

Revision ID: a6d1f22ef4c8
Revises: 5e56c954ef5b
Create Date: 2021-09-17 16:57:06.031332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d1f22ef4c8'
down_revision = '5e56c954ef5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'notes')
    # ### end Alembic commands ###
